import type { Message } from "@/lib/chat";

export function generateReport(messages: Message[]): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  let report = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>DermSight Report - ${dateStr}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a2e; }
  .header { text-align: center; border-bottom: 3px solid #1E88E5; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { color: #1E88E5; margin: 0; font-size: 28px; }
  .header p { color: #666; margin: 5px 0; }
  .badge { display: inline-block; background: #00BFA5; color: white; padding: 4px 12px; border-radius: 12px; font-size: 12px; }
  .section { margin-bottom: 24px; }
  .section-title { color: #1E88E5; font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; }
  .message { background: #f8f9fa; border-radius: 8px; padding: 16px; margin-bottom: 12px; border-left: 4px solid #1E88E5; }
  .message.user { border-left-color: #1E88E5; }
  .message.assistant { border-left-color: #00BFA5; }
  .message .role { font-weight: 600; font-size: 12px; text-transform: uppercase; color: #666; margin-bottom: 6px; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #eee; text-align: center; color: #999; font-size: 12px; }
  .disclaimer { background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 16px; margin-top: 30px; }
  .disclaimer h3 { color: #856404; margin: 0 0 8px; }
  .disclaimer p { color: #856404; margin: 0; font-size: 13px; }
  .image-note { color: #666; font-style: italic; font-size: 13px; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
  <div class="header">
    <h1>🩺 DermSight</h1>
    <p>AI Dermatology Assessment Report</p>
    <p>${dateStr} at ${timeStr}</p>
    <span class="badge">AI-Generated Report</span>
  </div>
`;

  // Filter out the welcome message
  const relevantMessages = messages.filter((m, i) => !(i === 0 && m.role === "assistant"));

  report += `<div class="section"><div class="section-title">Consultation Log</div>`;

  for (const msg of relevantMessages) {
    const role = msg.role === "user" ? "Patient" : "DermSight AI";
    const text = typeof msg.content === "string"
      ? msg.content
      : msg.content.filter((c) => c.type === "text").map((c) => (c as any).text).join("\n");

    report += `<div class="message ${msg.role}">
      <div class="role">${role}</div>
      <div>${text.replace(/\n/g, "<br/>")}</div>
      ${msg.imageUrl ? '<p class="image-note">📷 Skin image was uploaded for analysis</p>' : ""}
    </div>`;
  }

  report += `</div>

  <div class="disclaimer">
    <h3>⚠️ Important Disclaimer</h3>
    <p>This report is generated by an AI assistant and is for informational purposes only. It does NOT constitute a medical diagnosis, professional medical advice, or treatment recommendation. The AI assessment may not be accurate. Always consult a board-certified dermatologist or healthcare provider for proper evaluation, diagnosis, and treatment of any skin condition. Never delay seeking professional medical advice because of information in this report.</p>
  </div>

  <div class="footer">
    <p>Generated by DermSight AI • ${dateStr}</p>
    <p>This document is for personal reference only</p>
  </div>
</body>
</html>`;

  return report;
}

export function downloadReport(messages: Message[]) {
  const html = generateReport(messages);
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `DermSight-Report-${new Date().toISOString().split("T")[0]}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
